import opensim as osim
import os
import math
import time
import yaml

def load_config(config_path):
    """Loads configuration from a YAML file."""
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)

def run_simbody_visualization(config_path, speed_step=10, start_time_sec=0.0):
    """
    Visualizes an OpenSim state trajectory in Simbody.
    speed_step: 1 = All frames (Slow), 10 = 1 in 10 frames (Fast)
    start_time_sec: Time in seconds to start visualization
    """
    config = load_config(config_path)
    paths = config['paths']
    os_settings = config['opensim_settings']
    
    work_dir = os.getcwd()
    
    # We must construct the path to the calibrated model generated by the IK step
    out_dir = paths['output_folder']
    calibrated_model_path = os.path.join(work_dir, out_dir, os_settings['output_model_name'])
    
    # Check for MOT/STO files from IK
    ik_results_dir = os.path.join(work_dir, out_dir)
    motion_files = [f for f in os.listdir(ik_results_dir) if f.endswith(".mot") or f.endswith(".sto")]
    
    # Ignore the input orientation file if possible, prefer the IK result
    motion_files = [f for f in motion_files if f != paths['output_filename']]
    
    if not motion_files:
        print(f"ERROR: No motion files (.mot/.sto) found in {ik_results_dir} for visualization.")
        return False
        
    motion_file_path = os.path.join(ik_results_dir, motion_files[0])
    
    geometry_path = os.path.join(work_dir, paths['geometry_path'])
    if os.path.exists(geometry_path):
        osim.ModelVisualizer.addDirToGeometrySearchPaths(geometry_path)

    if not os.path.exists(calibrated_model_path):
        print(f"ERROR: Calibrated model not found at {calibrated_model_path}. Run pipeline first.")
        return False

    print(f"\n--- 3. Visualizing with Simbody: {os.path.basename(motion_file_path)} ---")

    # Load Model and set visualizer
    model_calibrated = osim.Model(calibrated_model_path)
    model_calibrated.setUseVisualizer(True)
    state = model_calibrated.initSystem()
    visualizer = model_calibrated.updVisualizer().updSimbodyVisualizer()
    visualizer.setBackgroundColor(osim.Vec3(0.2, 0.2, 0.2))

    # Load Data
    table = osim.TimeSeriesTable(motion_file_path)
    times = table.getIndependentColumn()
    n_rows = table.getNumRows()

    # Optimization: Cache coordinates
    print("Optimizing coordinate cache...")
    coord_map = []
    for j in range(table.getNumColumns()):
        col_name = table.getColumnLabel(j)
        if model_calibrated.getCoordinateSet().contains(col_name):
            coord_obj = model_calibrated.updCoordinateSet().get(col_name)
            coord_map.append((j, coord_obj))

    # Find starting frame
    start_index = 0
    for k in range(n_rows):
        if times[k] >= start_time_sec:
            start_index = k
            break

    print(f"Starting at {times[start_index]:.2f}s | Skipping every {speed_step} frames.")

    # Playback Loop
    try:
        for i in range(start_index, n_rows, speed_step):
            row = table.getRowAtIndex(i)
            
            for col_idx, coord_obj in coord_map:
                val_deg = row.getElt(0, col_idx)
                # Convert degrees to radians as per original implementation
                coord_obj.setValue(state, math.radians(val_deg)) 
            
            model_calibrated.realizePosition(state)
            visualizer.drawFrameNow(state)
            
            print(f"Time: {times[i]:.2f} s", end='\r')
            time.sleep(0.005) # Small delay to allow renderer to catch up

    except KeyboardInterrupt:
        print("\nStopped.")

    print("\nFinish.")
    return True
