# Linux Configuration

paths:
  input_folder: "/home/drims/data/sensors_data/8-abr-2026/V1"
  output_folder: "/home/drims/data/dataset_processing/Inverse_Kinematics_Opensim/8-abr-2026/V1"
  output_filename: "kinematics_v3.sto"
  mapping_file: "sensor_mapping.json"
  model_path: "models/Rajagopal_FreeArms_LockedLegs.osim"
  geometry_path: "models/Geometry"
  mujoco_output_folder: "/home/drims/data/dataset_processing/MuJoCo_Biomechanical_Model/8-abr-2026/V1"

settings:
  sampling_rate: 100.0

opensim_settings:
  base_imu_label: "pelvis_imu"
  base_heading_axis: "-z"
  sensor_to_opensim_rot: [-1.57079633, 0, 0] # -pi/2 on X axis
  output_model_name: "calibrated_model.osim"
