# Linux Configuration

paths:
  input_folder: "/home/drims/drims_ws/simulation_projects/IRL_Dataset/Sensors_Data/MUESTRAS2-XSENS/V2/IMU"
  output_folder: "/home/drims/drims_ws/simulation_projects/IRL_Dataset/IK_and_Movements"
  output_filename: "kinematics_v3.sto"
  mapping_file: "sensor_mapping.json"
  model_path: "models/Rajagopal_FreeArms_LockedLegs.osim"
  geometry_path: "models/Geometry"
  mujoco_output_folder: "/home/drims/drims_ws/simulation_projects/IRL_Dataset/MuJoCo_Biomechanical_Model"

settings:
  sampling_rate: 60.0

opensim_settings:
  base_imu_label: "pelvis_imu"
  base_heading_axis: "-z"
  sensor_to_opensim_rot: [-1.57079633, 0, 0] # -pi/2 on X axis
  output_model_name: "calibrated_model.osim"
